from typing import List, TypedDict, Annotated
import operator

class AgentState(TypedDict):
    """
    State schema for the multi-agent development team.
    Tracks the prompt, code, review feedback, and iteration counters to prevent infinite loops.
    """
    task: str                        # The primary task assigned by the user
    code: str                        # The current code generated by the Coder
    review_feedback: str             # Feedback and suggestions from the Reviewer
    current_iteration: int           # Current iteration counter
    max_iterations: int              # Maximum allowed iterations to prevent infinite loops
    messages: Annotated[List[str], operator.add]  # Cumulative log of messages between agents

    # Temporary test block (can be deleted later)
if __name__ == "__main__":
    initial_state: AgentState = {
        "task": "Build a simple calculator in Python",
        "code": "",
        "review_feedback": "",
        "current_iteration": 0,
        "max_iterations": 3,
        "messages": ["System initialized successfully."]
    }
    print("State Schema Loaded Successfully!")
    print(initial_state)